services:
  - docker:dind

pytest:
  image: python:3.6-stretch
  stage: build
  script:
    - cd app
    - pip install setuptools==39.2.0
    - python -m pip install pip==9.0.3
    - pip install pipenv
    - pipenv install --ignore-pipfile
    - pipenv install -d
    - pipenv run python setup.py install
    - pipenv run python -m pytest

build-app:
  image: docker:latest
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY/davelush/slack-bot-kudos/app" ./app/
    - docker push "$CI_REGISTRY/davelush/slack-bot-kudos/app"
  only:
    - master

build-dbmigrate:
  image: docker:latest
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY/davelush/slack-bot-kudos/dbmigrate" ./db/
    - docker push "$CI_REGISTRY/davelush/slack-bot-kudos/dbmigrate"
  only:
    - master

#
#build:
#  image: docker:latest
#  before_script:
#    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#  stage: build
#  script:
#    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
#    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
#  except:
#    - master