test:
  image: python:3.7-stretch
  script:
    - echo "running something"
    - pip install setuptools==39.2.0
    - python -m pip install pip==9.0.3
    - pip install pipenv
    - pipenv install --ignore-pipfile
    - pipenv install -d
    - pipenv run python setup.py install
    - echo "finished doing pipenv dependency setup"
    - pipenv run pytest
